services:
  - type: web
    name: deliverx-ai-route
    env: node
    plan: free
    buildCommand: npm install && cd client && npm install --legacy-peer-deps && npm run build
    startCommand: node serve.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000